[package]
name = "param_builder"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A param list builder for tokio postgres"
repository = "https://github.com/SunnyCryptoProjects/param_builder"

[dependencies]
postgres-types = "0.2.4"
